# Generated by Django 4.1.1 on 2022-09-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkinfo',
            name='link_id',
            field=models.CharField(max_length=6),
        ),
    ]
